### ISSUE TITLE
zint and zuint don't need to use reflection

### ISSUE THREAD

**Issue by kostya-sh** [shawnsmithdev/zermelo#1]
Readme says

> The subpackages zuint and zint must still use reflection as the bit width (32/64) is only available at runtime.

However this is not correct. Bit width is available at build time and can be defined as constant: https://play.golang.org/p/IfKUhv0agJ

**Comment by shawnsmithdev** [comment]
Very nice! I'll remove the reflection code soon!

**Comment by shawnsmithdev** [comment]
Fixed, thanks!
