### ISSUE TITLE
Sorted slice detection is incorrect

### ISSUE THREAD

**Issue by opennota** [shawnsmithdev/zermelo#7]
The `sorted` variable will never become true:

https://github.com/shawnsmithdev/zermelo/blob/71f3d2cee9e588c954bdd6c1ad73de45444ed1a3/zuint32/zuint32.go#L48-L68

**Comment by shawnsmithdev** [comment]
hmmm... maybe it got lost in a copy/paste.  I think the sort test is only against uint64...

**Comment by shawnsmithdev** [comment]
- Confirmed this was only in `uint32` code
- Confirmed this caused the "sorted shortcut" code to not work at all
- Fixed in bugfix release `v1.0.4`

Thanks for catching this!
